plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-rescript.cjs
    spec: "https://github.com/reason-seoul/yarn-plugin-rescript/releases/download/v0.0.0-5406022/plugin-rescript.js"

yarnPath: .yarn/releases/yarn-berry.cjs
